kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cp4x-verify-cr
rules:
- apiGroups: [""] 
  resources: ["pods", "secrets", "namespaces"]
  verbs: ["get", "patch", "list"]
- apiGroups: ["route.openshift.io"] 
  resources: ["routes"]
  verbs: ["get", "patch", "list"]