apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cp4x-verify-verify-crb
  namespace: verify
subjects:
- kind: ServiceAccount
  name: cp4x-verify-sa
  namespace: verify
roleRef:
  kind: ClusterRole
  name: cp4x-verify-cr
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cp4x-verify-ics-crb
  namespace: ibm-common-services
subjects:
- kind: ServiceAccount
  name: cp4x-verify-sa
  namespace: verify
roleRef:
  kind: ClusterRole
  name: cp4x-verify-cr
  apiGroup: rbac.authorization.k8s.io
